spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/content_db}
    username: ${DB_USERNAME:content}
    password: ${DB_PASSWORD:1q2w3e4R!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: ${JWT_SECRET:fa0e515481049208926bf3199115485a6321c9f4138da7725bb1eecd8f67c5b6}
  expiration: 3600000
  refresh-expiration: 86400000
  redirect:
    onboarding: https://www.loventure.com/onboarding
    base: https://www.loventure.com/home
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your_google_client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
            client-secret: ${KAKAO_CLIENT_SECRET:your_kakao_client_secret}
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id
