spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server.config-server.svc.cluster.local:80
      name: content-service
      label: main
      fail-fast: false
  application:
    name: content-service
  jpa:
    open-in-view: false

 
