spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server.config-server.svc.cluster.local:80
      name: content-service
      label: main
      fail-fast: false
  application:
    name: content-service
  jpa:
    open-in-view: false

# Google Cloud Storage 설정 (프로덕션)
gcs:
  bucket-name: ${GCS_BUCKET_NAME:pit_bucket}
  credentials-path: ${GCS_CREDENTIALS_PATH:/etc/gcp/key.json}
  project-id: ${GCS_PROJECT_ID:pitterpetter-2}
